---
fixtures:
  repositories:
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
      ref: 4.0.0
  symlinks:
    dnsmasq: "#{source_dir}"
